@startuml vidage
start
  #CCCCCC:vidage]
  note
    dosage.js
  end note
  if (courbe enregistrée) then (OK) 
    stop
  endif
  :vidage burette -> <b>burette/vidange();
  note 
    change état burette
    change état becher
  end note
  :mise à jour des valeurs -> <b>dosage.datas/updValues();
  note
    - currentDosage
    - data
    - actualise data graphe -> <b>Highchart/hChart.updateSerie()
    - actualise data charts -> <b>dosage.graph/updGraphCharts()
  end note
  :change couleur becher -> <b>setColor();
  if (conductimetre) then (OK)
    :change text -> <b>setText() ;
  elseif (phmetre ?) then (ok)
    :change text -> <b>setText();
  elseif (potentiometre) then (OK)
    :change text -> <b>setText();
  endif
  
stop
@enduml
